package cn.edu.neusoft.parttime.model;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

public class FlyerManagement {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column flyer_management.id
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column flyer_management.name
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column flyer_management.phone
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	private String phone;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column flyer_management.address
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	private String address;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column flyer_management.requirement
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	private String requirement;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column flyer_management.person_count
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	private Integer personCount;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column flyer_management.pub_date
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	@JSONField(format = "yyyy-MM-dd HH:mm:ss")
	private Date pubDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column flyer_management.salary
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	private String salary;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column flyer_management.id
	 *
	 * @return the value of flyer_management.id
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column flyer_management.id
	 *
	 * @param id
	 *            the value for flyer_management.id
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column flyer_management.name
	 *
	 * @return the value of flyer_management.name
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column flyer_management.name
	 *
	 * @param name
	 *            the value for flyer_management.name
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column flyer_management.phone
	 *
	 * @return the value of flyer_management.phone
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column flyer_management.phone
	 *
	 * @param phone
	 *            the value for flyer_management.phone
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column flyer_management.address
	 *
	 * @return the value of flyer_management.address
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column flyer_management.address
	 *
	 * @param address
	 *            the value for flyer_management.address
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column flyer_management.requirement
	 *
	 * @return the value of flyer_management.requirement
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	public String getRequirement() {
		return requirement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column flyer_management.requirement
	 *
	 * @param requirement
	 *            the value for flyer_management.requirement
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	public void setRequirement(String requirement) {
		this.requirement = requirement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column flyer_management.person_count
	 *
	 * @return the value of flyer_management.person_count
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	public Integer getPersonCount() {
		return personCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column flyer_management.person_count
	 *
	 * @param personCount
	 *            the value for flyer_management.person_count
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	public void setPersonCount(Integer personCount) {
		this.personCount = personCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column flyer_management.pub_date
	 *
	 * @return the value of flyer_management.pub_date
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	public Date getPubDate() {
		return pubDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column flyer_management.pub_date
	 *
	 * @param pubDate
	 *            the value for flyer_management.pub_date
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	public void setPubDate(Date pubDate) {
		this.pubDate = pubDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column flyer_management.salary
	 *
	 * @return the value of flyer_management.salary
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	public String getSalary() {
		return salary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column flyer_management.salary
	 *
	 * @param salary
	 *            the value for flyer_management.salary
	 *
	 * @mbg.generated Thu Mar 07 17:21:22 CST 2019
	 */
	public void setSalary(String salary) {
		this.salary = salary;
	}
}