package cn.edu.neusoft.parttime.model;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

public class Resume {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resume.id
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resume.name
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resume.gender
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	private String gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resume.email
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resume.phone
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resume.profile
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	private String profile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resume.job_type
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	private String jobType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resume.job_id
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	private Integer jobId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resume.pub_date
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	@JSONField(format = "yyyy-MM-dd HH:mm:ss")
	private Date pubDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resume.id
	 * @return  the value of resume.id
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resume.id
	 * @param id  the value for resume.id
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resume.name
	 * @return  the value of resume.name
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resume.name
	 * @param name  the value for resume.name
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resume.gender
	 * @return  the value of resume.gender
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resume.gender
	 * @param gender  the value for resume.gender
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resume.email
	 * @return  the value of resume.email
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resume.email
	 * @param email  the value for resume.email
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resume.phone
	 * @return  the value of resume.phone
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resume.phone
	 * @param phone  the value for resume.phone
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resume.profile
	 * @return  the value of resume.profile
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	public String getProfile() {
		return profile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resume.profile
	 * @param profile  the value for resume.profile
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	public void setProfile(String profile) {
		this.profile = profile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resume.job_type
	 * @return  the value of resume.job_type
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	public String getJobType() {
		return jobType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resume.job_type
	 * @param jobType  the value for resume.job_type
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	public void setJobType(String jobType) {
		this.jobType = jobType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resume.job_id
	 * @return  the value of resume.job_id
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	public Integer getJobId() {
		return jobId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resume.job_id
	 * @param jobId  the value for resume.job_id
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	public void setJobId(Integer jobId) {
		this.jobId = jobId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resume.pub_date
	 * @return  the value of resume.pub_date
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	public Date getPubDate() {
		return pubDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resume.pub_date
	 * @param pubDate  the value for resume.pub_date
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	public void setPubDate(Date pubDate) {
		this.pubDate = pubDate;
	}
}