package cn.edu.neusoft.parttime.dao;

import java.util.List;

import cn.edu.neusoft.parttime.model.FlyerManagement;

public interface FlyerManagementMapper {
	List<FlyerManagement> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyer_management
     *
     * @mbg.generated Thu Mar 07 17:21:22 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyer_management
     *
     * @mbg.generated Thu Mar 07 17:21:22 CST 2019
     */
    int insert(FlyerManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyer_management
     *
     * @mbg.generated Thu Mar 07 17:21:22 CST 2019
     */
    int insertSelective(FlyerManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyer_management
     *
     * @mbg.generated Thu Mar 07 17:21:22 CST 2019
     */
    FlyerManagement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyer_management
     *
     * @mbg.generated Thu Mar 07 17:21:22 CST 2019
     */
    int updateByPrimaryKeySelective(FlyerManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyer_management
     *
     * @mbg.generated Thu Mar 07 17:21:22 CST 2019
     */
    int updateByPrimaryKey(FlyerManagement record);
}