package cn.edu.neusoft.parttime.dao;

import java.util.List;

import cn.edu.neusoft.parttime.model.FlyerManagement;
import cn.edu.neusoft.parttime.model.RepastManagement;

public interface FlyerManagementMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table flyer_management
	 * @mbg.generated  Tue Mar 12 16:43:29 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table flyer_management
	 * @mbg.generated  Tue Mar 12 16:43:29 CST 2019
	 */
	int insert(FlyerManagement record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table flyer_management
	 * @mbg.generated  Tue Mar 12 16:43:29 CST 2019
	 */
	int insertSelective(FlyerManagement record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table flyer_management
	 * @mbg.generated  Tue Mar 12 16:43:29 CST 2019
	 */
	FlyerManagement selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table flyer_management
	 * @mbg.generated  Tue Mar 12 16:43:29 CST 2019
	 */
	int updateByPrimaryKeySelective(FlyerManagement record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table flyer_management
	 * @mbg.generated  Tue Mar 12 16:43:29 CST 2019
	 */
	int updateByPrimaryKey(FlyerManagement record);
	List<FlyerManagement> selectLatest(int number);
	List<FlyerManagement> selectAll();
}