package cn.edu.neusoft.parttime.dao;

import java.util.List;

import cn.edu.neusoft.parttime.model.RepastManagement;

public interface RepastManagementMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repast_management
	 * @mbg.generated  Tue Mar 12 16:43:29 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repast_management
	 * @mbg.generated  Tue Mar 12 16:43:29 CST 2019
	 */
	int insert(RepastManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repast_management
	 * @mbg.generated  Tue Mar 12 16:43:29 CST 2019
	 */
	int insertSelective(RepastManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repast_management
	 * @mbg.generated  Tue Mar 12 16:43:29 CST 2019
	 */
	RepastManagement selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repast_management
	 * @mbg.generated  Tue Mar 12 16:43:29 CST 2019
	 */
	int updateByPrimaryKeySelective(RepastManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repast_management
	 * @mbg.generated  Tue Mar 12 16:43:29 CST 2019
	 */
	int updateByPrimaryKey(RepastManagement record);

	List<RepastManagement> selectLatest(int number);
	 
	List<RepastManagement> selectAll();
}