package cn.edu.neusoft.parttime.dao;

import java.util.List;

import cn.edu.neusoft.parttime.model.RepastManagement;

public interface RepastManagementMapper {
	List<RepastManagement> selectLatest(int number);
	 
	List<RepastManagement> selectAll();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repast_management
     *
     * @mbg.generated Thu Mar 07 17:21:22 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repast_management
     *
     * @mbg.generated Thu Mar 07 17:21:22 CST 2019
     */
    int insert(RepastManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repast_management
     *
     * @mbg.generated Thu Mar 07 17:21:22 CST 2019
     */
    int insertSelective(RepastManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repast_management
     *
     * @mbg.generated Thu Mar 07 17:21:22 CST 2019
     */
    RepastManagement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repast_management
     *
     * @mbg.generated Thu Mar 07 17:21:22 CST 2019
     */
    int updateByPrimaryKeySelective(RepastManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repast_management
     *
     * @mbg.generated Thu Mar 07 17:21:22 CST 2019
     */
    int updateByPrimaryKey(RepastManagement record);
}