package cn.edu.neusoft.parttime.dao;

import java.util.List;

import cn.edu.neusoft.parttime.model.Resume;

public interface ResumeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resume
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resume
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	int insert(Resume record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resume
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	int insertSelective(Resume record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resume
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	Resume selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resume
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	int updateByPrimaryKeySelective(Resume record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resume
	 * @mbg.generated  Sun May 12 02:28:35 CST 2019
	 */
	int updateByPrimaryKey(Resume record);

	/**
	 * @return
	 */
	List<Resume> selectAll();
}