package cn.edu.neusoft.parttime.dao;

import java.util.List;

import cn.edu.neusoft.parttime.model.FlyerManagement;
import cn.edu.neusoft.parttime.model.SupermarketManagement;

public interface SupermarketManagementMapper {
	List<SupermarketManagement> selectLatest(int number);
	List<SupermarketManagement> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supermarket_management
     *
     * @mbg.generated Thu Mar 07 17:21:22 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supermarket_management
     *
     * @mbg.generated Thu Mar 07 17:21:22 CST 2019
     */
    int insert(SupermarketManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supermarket_management
     *
     * @mbg.generated Thu Mar 07 17:21:22 CST 2019
     */
    int insertSelective(SupermarketManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supermarket_management
     *
     * @mbg.generated Thu Mar 07 17:21:22 CST 2019
     */
    SupermarketManagement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supermarket_management
     *
     * @mbg.generated Thu Mar 07 17:21:22 CST 2019
     */
    int updateByPrimaryKeySelective(SupermarketManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supermarket_management
     *
     * @mbg.generated Thu Mar 07 17:21:22 CST 2019
     */
    int updateByPrimaryKey(SupermarketManagement record);
}