package cn.edu.neusoft.parttime.dao;

import java.util.List;

import cn.edu.neusoft.parttime.model.User;

public interface UserMapper {
	Integer countAdmin();
	
	
	User selectByUsername(String username);
	
	List<User> selectAll();
 
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Mar 06 21:56:08 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Mar 06 21:56:08 CST 2019
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Mar 06 21:56:08 CST 2019
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Mar 06 21:56:08 CST 2019
	 */
	User selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Mar 06 21:56:08 CST 2019
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Wed Mar 06 21:56:08 CST 2019
	 */
	int updateByPrimaryKey(User record);
}